function functie(R,C,grid_on_off)


% Crearea figurii
Fig = figure('Name', 'Caracteristica de frecventa ale filtrului RC trece-jos', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.2 0.8 0.7], ...
             'Color','#d2d24e',...
             'NumberTitle', 'off'); 



% Datele pentru filtru
  f0=1./(2.*pi.*R.*C);
  w0=2.*pi.*f0;
  puncte_grafic=100;
  w=logspace(-2,4, puncte_grafic);
  f=w/(2*pi);

  %functia de transfer
 jos= 1 + j*w*R*C;
 H_mod=abs(1./jos);
 faza=angle(1./jos)*180./pi;
 
% semnal grid radio button 
btnSemnal = uibuttongroup('Visible', 'on', ...
    'FontWeight', 'bold', ...
    'BackgroundColor','#dc7633' , ...
    'ForegroundColor', 'black', ...
    'Fontname', 'Comic Sans MS', ...
    'Title', 'Semnal:', ...
    'FontSize', 17, ...
    'TitlePosition', 'centertop', ...
    'Position', [0.7, 0, 0.2, 0.2],...
    'HighlightColor', '#dc7633', ... 
    'ShadowColor', '#dc7633');



uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.70 0.2 0.2 0.11],...
          'string',' Valori Standard ',...
          'FontName','Calibri',...
          'FontSize',20,...
          'Backgroundcolor','y',...
          'Callback','open standard.pdf');





% GRID
uicontrol('style','text',...
          'Units','normalized',...
          'String','Grid:',...
           'BackgroundColor','#f39c12',...
           'ForegroundColor','black',...
          'FontWeight', 'bold',...
          'FontSize',12,...
          'Position',[0.05 0.3 0.5 0.4],...
          'Parent',btnSemnal);
 
    RadioB1=uicontrol('style','radiobutton',...
          'Units','normalized',...
           'BackgroundColor','#9a7d0a',...
           'ForegroundColor','black',...
          'String','ON',...
          'FontWeight', 'bold',...
          'FontSize',12,...
          'Position',[0.5 0.3 0.5 0.4],...
          'Parent',btnSemnal,...
          'Callback','grid_on_off=1,close;functie(R,C,grid_on_off);');
      
      RadioB2=uicontrol('style','radiobutton',...
          'Units','normalized',...
           'BackgroundColor','#9a7d0a',...
           'ForegroundColor','black',...
          'String','OFF',...
          'FontWeight', 'bold',...
          'FontSize',12,...
          'Position',[0.7 0.3 0.5 0.4],...
          'Parent',btnSemnal,...
          'Callback','grid_on_off=2,close;functie(R,C,grid_on_off);');

   

%Grafic Ui/Uo

 subplot(221);
 set(gca, 'Position', [0.05, 0.55, 0.4, 0.4]);
 semilogx(f,H_mod,f0,1./sqrt(2),'-ob','LineWidth',2); % -3db -1/rad2
 xlabel('Frecventa [ Hz ]');
 ylabel('| Vou/ Vin | ');
 title('Caracteristica  |Vout / Vin |', ...
       'Fontweight','b','Color','black');
 legend(' |Vout / Vin |');

 % Selectia grid ului

 if grid_on_off == 1
set(RadioB1,'value',1)
set(RadioB2,'value',0)
grid on;
else
set(RadioB1,'value',0)
set(RadioB2,'value',1)
grid off;
 end


 % Grafic faza
 subplot(223);
 set(gca, 'Position', [0.05, 0.05, 0.4, 0.4])
 semilogx(f,faza,'r',f0,-45,'d','LineWidth',2);
 xlabel('Frecventa [ Hz ]');
 ylabel('Faza [ grade ]');
 title('Faza semnalului',...
       'Fontweight','b','Color','black');
 legend('Faza');
 
 if grid_on_off == 1
set(RadioB1,'value',1)
set(RadioB2,'value',0)
grid on;
else
set(RadioB1,'value',0)
set(RadioB2,'value',1)
grid off;
 end


 % Buton Inapoi

 uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.53 0.012 0.1 0.05],...
          'string','Inapoi',...
          'FontName','Times New Roman',...
          'backgroundcolor','#9cbf00',...
          'foregroundcolor','#000000',...
          'FontSize',19,...          
          'Callback','start');
    % Chenar date
chenardate=uibuttongroup('Visible','on',...
        'BackgroundColor','#f7dc6f',...
        'ForegroundColor','black',...
        'Position',[0.675 0.41 0.3 0.62],... 
        'TitlePosition','centertop',...
        'Tag','radiobutton');

% Butoane pentru caracteristica filtrului
RadioGroup1=uibuttongroup('Visible','on',...
        'BackgroundColor','#f1c40f',...
        'ForegroundColor','black',...
        'Title','Valori ',...
        'FontSize',19,...
        'Position',[0.11 0.42 0.78 0.45],... 
        'FontWeight','Bold',...
        'Fontname','Calibri',...
        'TitlePosition','centertop',...
        'Parent',chenardate,...
        'HighlightColor', '#f1c40f', ... 
        'ShadowColor', '#f1c40f',...
        'Tag','radiobutton');

% Rezistenta

rt = uicontrol('Style','text',... 
        'Units','normalized', ...
        'Position',[0.19 0.750 0.4 0.23], ...
        'backgroundcolor','#ca6f1e', ...
        'foregroundcolor','black', ...
        'FontSize',15, ...
        'String','R[Ω]', ...
        'FontWeight','Bold', ...
        'Parent',RadioGroup1);
re = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[0.65 0.75 0.3 0.23], ...
        'FontSize',15, ...
        'String', R, ...
        'FontWeight','Bold', ...
        'Parent',RadioGroup1, ...
        'Callback','R=str2num(get(gco,''String'')),close,functie(R,C,grid_on_off)');

% Capacitate

ct = uicontrol('Style','text', ... 
        'Units','normalized', ...
        'Position',[0.19 0.45 0.4 0.23], ...
        'backgroundcolor','#ca6f1e', ...
        'foregroundcolor','black', ...
        'FontSize',15, ...
        'FontWeight','Bold', ...
        'String','C[Farad]', ...
        'Parent',RadioGroup1);
ce = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[0.65 0.45 0.3 0.23], ...
        'FontSize',15, ...
        'String', C, ...
        'FontWeight','Bold', ...
        'Parent',RadioGroup1, ...
        'Callback','C=str2num(get(gco,''String'')),close,functie(R,C,grid_on_off)');



% Calcul frecventa de taiere 
RadioGroup2=uibuttongroup('Visible','on',...
        'BackgroundColor','#f1c40f',...
        'ForegroundColor','black',...
        'Title','Frecventa de taiere',...
        'FontSize',15,...
        'Position',[0.08 0.1 0.8 0.30],... 
        'FontWeight','Bold',...
        'Fontname','Comic Sans MS',...
        'TitlePosition','centertop',...
        'Parent',chenardate,...
        'HighlightColor', '#f1c40f', ... 
        'ShadowColor', '#f1c40f',...
        'Tag','radiobutton');

uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.1 0.025 0.86 0.7],...
        'backgroundcolor','#ca6f1e',...
        'foregroundcolor','black',...
        'FontWeight','Bold',...
        'FontSize',15,...
        'String',['Fo[Hz] = ',num2str(f0)],...
        'Parent',RadioGroup2);

% Pulsatie   calcul
RadioGroup3=uibuttongroup('Visible','on',...
        'BackgroundColor','#f1c40f',...
        'ForegroundColor','black',...
        'Title','Pulsatia',...
        'FontSize',15,...
        'Position',[0.08 0.010 0.8 0.18],... 
        'FontWeight','Bold',...
        'Fontname','Comic Sans MS',...
        'TitlePosition','centertop',...
        'Parent',chenardate,...
         'HighlightColor', '#f1c40f', ... 
        'ShadowColor', '#f1c40f',...
        'Tag','radiobutton');

uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.1 0.025 0.86 0.7],...
        'backgroundcolor','#ca6f1e',...
        'foregroundcolor','black',...
        'FontWeight','Bold',...
        'FontSize',15,...
        'String',['wo[rad/s]= ',num2str(w0)],...
        'Parent',RadioGroup3);


