

function Semnale()

    R_initial = 1000;
    C_initial = 1e-6;
    A_initial = 10;
    f = 1000;

    % Crearea figurii
    fig = figure('Name', 'Filtru Trece-Jos RC ', ...
                 'Units', 'normalized', ...
                 'Color','#d8d833',... 
                 'Position', [0.1 0.1 0.8 0.8], ...
                 'NumberTitle', 'off');

    % Grafic
    ax = axes('Units', 'normalized', 'Position', [0.1 0.35 0.8 0.6]);
    hold(ax, 'on');
    xlabel(ax, "Timp [Secunde]");
    ylabel(ax, "Amplitudine [Volți]");
    title(ax, 'Semnalele de intrare/iesire a unui FTJ');
    grid(ax, 'on');
    legend(ax);

% Buton resetare

buton_Reset = uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.85 0.012 0.1 0.05],... 
          'string','Reset',...
          'FontName','Times New Roman',...
          'FontWeight','Bold',...
          'backgroundcolor','#e74c3c',... 
          'foregroundcolor','#000000',... 
          'FontSize',19,...          
          'Callback', @resetare); 

% Funcția de resetare
function resetare(~, ~)
    sldR.Value = R_initial;
    sldC.Value = C_initial;
    sldA.Value = A_initial;

    % Revenire la valorile initiale
    set(txtR, 'String', ['R = ' num2str(R_initial) ' Ω']);
    set(txtC, 'String', ['C = ' num2str(C_initial) ' F']);
    set(txtA, 'String', ['A = ' num2str(A_initial) ' V']);

    % Actualizat graficul la valorile initiale
    actualizare_grafic(R_initial, C_initial, A_initial);
end


    % Buton Inapoi
    uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.45 0.012 0.1 0.05],...
          'string','Inapoi',...
          'FontName','Times New Roman',...
          'FontWeight','Bold',...
          'backgroundcolor','#f1c40f',... 
          'foregroundcolor',[0 0 0],... 
          'FontSize',19,...          
          'Callback','start'); 

    % Funcția pentru a actualiza graficul
    function actualizare_grafic(R, C, A)
    ft = 1 ./ (2 .* pi .* R .* C);         
    T = 1 ./ ft;                          
    t = 0:T/100:2*T;                      
    Vi = A .* sin(2 .* pi .* f .* t);  
    jos2 = sqrt(1 + (f ./ ft).^2);
    H_modul = 1 ./ jos2;  
    Vo = H_modul .* A .* sin(2 .* pi .* f .* t); % Semnalul de ieșire
        cla(ax);
        plot(ax, t, Vi, '-or', ...
            'DisplayName', 'Vintrare');
        plot(ax, t, Vo, '-db', ...
            'DisplayName', 'Viesire');
        legend(ax);
    end

    % Sliderele  pentru R C A
    sldR = uicontrol('Style', 'slider', ...
        'Units', 'normalized', ...
        'Position', [0.1 0.2 0.8 0.05], ...
        'BackgroundColor','#9a7d0a', ...
        'Min', 100, 'Max', 2200, ...
        'Value', R_initial, ...
        'SliderStep', [0.01 0.1], ...
        'Callback', @actualizare_tot);
    sldC = uicontrol('Style', 'slider', ...
        'Units', 'normalized', ...
        'Position', [0.1 0.15 0.8 0.05], ...
        'BackgroundColor','#f1c40f', ...
        'Min', 1e-7, 'Max', 1e-5, ...
        'Value', C_initial, ...
        'SliderStep', [0.01 0.1], ...
        'Callback', @actualizare_tot);
    sldA = uicontrol('Style', 'slider', ...
        'Units', 'normalized', ...
        'Position', [0.1 0.1 0.8 0.05], ...
        'BackgroundColor','#9a7d0a', ...
        'Min', 1, 'Max', 20, ...
        'Value', A_initial, ...
        'SliderStep', [0.01 0.1], ...
        'Callback', @actualizare_tot);

    % Text insotire slider
    txtR = uicontrol('Style','text', ...
        'Units','normalized', ...
        'Position',[0.01 0.2 0.08 0.05], ...
        'BackgroundColor','#c61b1b', ...
        'FontSize',9, ...
        'String',['R = ' num2str(R_initial) ' Ω']);
    txtC = uicontrol('Style','text', ...
        'Units','normalized', ...
        'Position',[0.01 0.15 0.08 0.05], ...
        'BackgroundColor','#b78420', ...
        'String',['C = ' num2str(C_initial) ' F']);
    txtA = uicontrol('Style','text', ...
        'Units','normalized', ...
        'Position',[0.01 0.1 0.08 0.05], ...
        'BackgroundColor','#c61b1b', ...
        'String',['A = ' num2str(A_initial) ' V']);

  

    % Funcția callback pentru toate sliderele
    function actualizare_tot(~, ~) 
        R = sldR.Value;
        C = sldC.Value;
        A = sldA.Value;
        actualizare_grafic(R, C, A);
        set(txtR, 'String', ['R = ' num2str(R) ' Ω']);
        set(txtC, 'String', ['C = ' num2str(C) ' F']);
        set(txtA, 'String', ['A = ' num2str(A) ' V']);
    end


  % Buton Checkbox Grila
    chkGrid = uicontrol('Style', 'checkbox', ...
        'Units', 'normalized', ...
        'Position', [0.01 0.9 0.05 0.15], ...
        'BackgroundColor','#d83333', ...
        'String', 'Grilă', ...
        'FontSize',14, ...
        'Value', 1, ...
        'Callback', {@functie_grid, ax});

    % Functia callback pentru grila
    function functie_grid(grid_initial, ~, ax)
        if grid_initial.Value == 1
            grid(ax, 'on');
        else
            grid(ax, 'off');
        end
    end

    % Apel inițial
    actualizare_tot(sldR, []);
end