% Pagina de start

Fig=figure('Name','Proiect',... 
           'Units','normalized',...
           'Position',[0.1 0.1 0.8 0.8],...
           'NumberTitle','off');
         
x = imread('wallpaperflare.jpg'); 
image(x);
set(gca,'Position',[0 0 1 1]);
axis off;

uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.3 0.8 0.379 0.1],...
'BackgroundColor','w',...
'Fontname','Calibri',...
'FontSize',24,...
'string','Filtru trece-jos - RC');
      
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.04 0.2 0.2 0.11],...
          'Backgroundcolor','w',...
          'string',' Grafice ',...
          'FontName','Calibri',...
          'FontSize',20,...
          'Callback','proiectftj');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.35 0.1 0.3 0.11],...
          'string',' Prezentare ',...
          'FontName','Calibri',...
          'FontSize',20,...
          'Backgroundcolor','w',...
          'Callback','open (''Project.pptx'')');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.77 0.2 0.2 0.11],...
          'string',' Documentație ',...
          'FontName','Calibri',...
          'FontSize',20,...
          'Backgroundcolor','w',...
          'Callback','open ftj_doc.docx');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.04 0.1 0.2 0.11],...
          'Backgroundcolor','w',...
          'string',' Semnale ',...
          'FontName','Calibri',...
          'FontSize',20,...
          'Callback','Semnale ');